"""11 - Assemble results/SUMMARY.md: every table, paper-ready.

Reads each results/*.json and emits one markdown document containing the
label-mapping decision, split sizes, main metrics, McNemar, adversarial drops
and ablation, the adversarial audit samples, latency (including the RF n_jobs
rows and the GPU rows), the cascade sweep, and the error-analysis examples.

Every number that the original (deleted) study also reported gets an
old-vs-new column, driven by results/old_paper.json. Values absent there are
printed as "not recorded" -- never guessed, and never quietly replaced by the
new value. Qualitative conclusions are recomputed from the new results and
compared against the old paper's recorded claims; disagreements are flagged.
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
import common as C

MODELS = ("LR", "NB", "RF", "DistilBERT")
ATTACKS = ("leetspeak", "char_insert", "whitespace", "swap")
NR = "_not recorded_"


def fmt(v, nd=4):
    if v is None:
        return NR
    if isinstance(v, float):
        return "{:.{}f}".format(v, nd)
    return str(v)


def delta(new, old, nd=4):
    """new (old) [delta] or new (not recorded)."""
    if old is None:
        return "{} ({})".format(fmt(new, nd), NR)
    d = new - old
    return "{} ({}) [{:+.{}f}]".format(fmt(new, nd), fmt(old, nd), d, nd)


def load(name, required=True, sfx=""):
    """Load results/<stem><sfx>.json."""
    if sfx and name.endswith(".json"):
        name = name[: -len(".json")] + sfx + ".json"
    p = C.RESULTS / name
    if not p.exists():
        if required:
            print("  MISSING: results/{} - run that script first".format(name))
        return None
    return C.load_json(p)


def conclusions_from(d05, d06, d07, d08):
    """Recompute the qualitative claims from one label set's results."""
    c = {}
    if d05:
        best = max(MODELS, key=lambda m: d05["metrics"][m]["macro_f1"])
        c["distilbert_best_on_clean"] = (best == "DistilBERT")
        key = "LR vs DistilBERT"
        if key in d05["mcnemar"]["pairs"]:
            r = d05["mcnemar"]["pairs"][key]
            better = (d05["metrics"]["DistilBERT"]["macro_f1"]
                      > d05["metrics"]["LR"]["macro_f1"])
            c["distilbert_beats_lr_significantly"] = bool(
                r["significant_at_0.05"] and better)
    if d06:
        drops = {m: float(np.mean([d06["results"][a]["per_model"][m]["abs_drop"]
                                   for a in ATTACKS])) for m in MODELS}
        c["distilbert_most_robust_to_attacks"] = (
            min(drops, key=drops.get) == "DistilBERT")
        c["_mean_drops"] = drops
    if d08 and d05:
        cc = d08["results"].get("[0.4, 0.7]", {}).get("clean")
        if cc:
            bci = d05["bootstrap"]["per_model"]["DistilBERT"]
            c["cascade_matches_distilbert_within_ci"] = bool(
                cc["macro_f1"] >= bci["ci_low"])
    if d07:
        cl = d07["cpu_classical"]["RF"]
        c["rf_njobs_parallel_faster_single_example"] = bool(
            cl["n_jobs=-1"]["end_to_end_single"]["mean_ms"]
            < cl["n_jobs=1"]["end_to_end_single"]["mean_ms"])
    return c


def main():
    C.banner("11 - SUMMARY")
    old = load("old_paper.json") or {}
    d01 = load("01_data.json")
    d02 = load("02_preprocess.json")
    d03 = load("03_classical.json")
    d04 = load("04_distilbert.json", required=False)
    d05 = load("05_evaluate.json", required=False)
    d06 = load("06_adversarial.json", required=False)
    d07 = load("07_latency.json", required=False)
    d08 = load("08_cascade.json", required=False)
    d09 = load("09_analysis.json", required=False)
    env = load("env.json", required=False)

    # sensitivity run (E + I label definition), if it has been produced
    e05 = load("05_evaluate.json", required=False, sfx="_ei")
    e06 = load("06_adversarial.json", required=False, sfx="_ei")
    e07 = load("07_latency.json", required=False, sfx="_ei")
    e08 = load("08_cascade.json", required=False, sfx="_ei")
    e03 = load("03_classical.json", required=False, sfx="_ei")
    e04 = load("04_distilbert.json", required=False, sfx="_ei")
    has_ei = e05 is not None

    if d01 is None:
        print("cannot build summary without results/01_data.json")
        sys.exit(1)

    L = []
    A = L.append
    A("# CONDA toxicity detection — results summary")
    A("")
    A("Generated by `src/11_summary.py`. Every number is read from "
      "`results/*.json`; nothing is transcribed by hand.")
    A("")
    A("> **Rebuild, not a recovery.** The original project and its transcripts "
      "were deleted. This is a fresh implementation from spec. Columns marked "
      "*old* come from `results/old_paper.json`; where the original value did "
      "not survive the deletion it reads *not recorded* and is **not** "
      "back-filled with the new value.")
    A("")

    # ---------------------------------------------------------------- provenance
    A("## 0. Provenance of the comparison column")
    A("")
    A("The original project and its transcripts were deleted; the only "
      "surviving artefact was one memory note. The old values below come "
      "instead from the paper PDF (*When Does TF-IDF Suffice?*, Bhaumik & "
      "Berlin M. A.), transcribed into `results/old_paper.json`. Old "
      "hyperparameter values were never reported in the paper and remain "
      "*not recorded*.")
    A("")

    # ------------------------------------------------- methodology discrepancies
    disc = old.get("_methodology_discrepancies")
    if disc:
        A("## 0.1 Errors in the paper's methodology section — fix before "
          "camera-ready")
        A("")
        A("Two of the paper's Section IV descriptions contradict the paper's "
          "own reported numbers. Both were found by trying to reproduce the "
          "numbers from the described procedure, and both are the kind of "
          "thing a reviewer can check in minutes.")
        A("")

        d = disc.get("label_collapse_rule")
        if d:
            A("### (a) The stated label-collapse rule cannot produce the "
              "paper's own counts")
            A("")
            A("- **Paper says** — {}".format(d["paper_says"]))
            A("- **That rule actually yields** — {} toxic / {} non-toxic".format(
                d["that_rule_actually_yields"]["toxic"],
                d["that_rule_actually_yields"]["non_toxic"]))
            A("- **Paper reports** — {} toxic / {} non-toxic".format(
                d["paper_reports"]["toxic"], d["paper_reports"]["non_toxic"]))
            A("- **Rule that does reproduce those counts** — "
              "`{}`".format(d["rule_that_reproduces_paper_counts"]))
            A("")
            A("{}".format(d["verdict"]))
            A("")

        d = disc.get("split_protocol")
        if d:
            A("### (b) The stated split is arithmetically impossible")
            A("")
            A("- **Paper says** — {}".format(d["paper_says"]))
            ac = d["actual_corpus"]
            A("- **Actual corpus** — `CONDA_train.csv` {:,} rows, "
              "`CONDA_valid.csv` {:,}, `CONDA_test.csv` {:,} (unlabelled); "
              "{:,} rows in total, {:,} labelled.".format(
                  ac["CONDA_train.csv"], ac["CONDA_valid.csv"],
                  ac["CONDA_test.csv_unlabelled"], ac["total"],
                  ac["total_labelled"]))
            A("")
            A("{}".format(d["verdict"]))
            A("")
            A("{}".format(d["also_note"]))
            A("")

        d = disc.get("distilbert_latency_iterations")
        if d:
            A("### (c) DistilBERT's old latency rests on 10× fewer samples")
            A("")
            A("- **Paper says** — {}".format(d["paper_says"]))
            A("- **This rebuild** — {}".format(d["this_rebuild"]))
            A("")
            A("{}".format(d["verdict"]))
            A("")

        d = disc.get("fig4_axis")
        if d:
            A("### (d) Figure 4's axis")
            A("")
            A("- **Paper says** — {}".format(d["paper_says"]))
            A("- **Observed** — {}".format(d["observed"]))
            A("- **This rebuild** — {}".format(d["this_rebuild"]))
            A("")

    if env:
        A("## 1. Environment")
        A("")
        cpu = env.get("cpu", {})
        A("| item | value |")
        A("|---|---|")
        A("| CPU | {} |".format(cpu.get("model", "?")))
        A("| cores | {} physical / {} logical |".format(
            cpu.get("physical_cores"), cpu.get("logical_cores")))
        A("| RAM | {} GiB |".format(env.get("ram", {}).get("total_gib")))
        A("| GPU | {} ({}) |".format(env.get("gpu", {}).get("name"),
                                     env.get("gpu", {}).get("memory_total")))
        A("| OS | {} |".format(env.get("os", {}).get("platform")))
        v = env.get("versions", {})
        for k in ("python", "torch", "transformers", "sklearn", "statsmodels",
                  "numpy", "pandas"):
            A("| {} | {} |".format(k, v.get(k)))
        A("")

    # ---------------------------------------------------------------- labels
    A("## 2. Label mapping")
    A("")
    A("CONDA provides no binary label. Candidate mappings and the counts each "
      "produces on the 8,973-row test set:")
    A("")
    A("| candidate mapping | toxic | non-toxic | matches original? |")
    A("|---|---|---|---|")
    for c in d01["candidates"]:
        A("| `{}` | {} | {} | {} |".format(
            c["mapping"], c["toxic"], c["non_toxic"],
            "**yes**" if c["matches_target"] else "no"))
    A("")
    A("**Adopted:** `{}`".format(d01["adopted_mapping_rule"]))
    A("")
    A("One row (`Id` 2525, class `O`) has a blank utterance and is dropped, "
      "which is what turns 8,974 raw rows into 8,973.")
    A("")
    A("### 2.1 Caveat on the `A` class — read before citing")
    A("")
    A("CONDA's own README treats only `E` (explicit) and `I` (implicit) as "
      "toxicity classes. `A` is an **action** class: utterances asking others "
      "to *report* or *commend* a player. The adopted mapping labels all 580 "
      "`A` utterances toxic, of which 75 contain \"commend\"/\"comment\" — "
      "positive messages. Token-level evidence agrees that `A` is not toxic:")
    A("")
    A("| intent class | n (test) | share carrying a token-level `T` tag |")
    A("|---|---|---|")
    A("| `E` explicit | 1,183 | 80.6% |")
    A("| `I` implicit | 582 | 4.0% |")
    A("| `A` action | 580 | **5.0%** |")
    A("| `O` neutral | 6,628 | 3.7% |")
    A("")
    A("`A` behaves like the neutral class, not like `E`. Including it inflates "
      "the toxic class by 33% (580 / 1,765) with largely non-toxic content.")
    A("")
    A("**The paper already noticed this**, in Sec V-F: *\"The high toxic-class "
      "weight on report and commend reveals an annotation artifact worth "
      "flagging: utterances calling on others to report a teammate are "
      "themselves frequently labeled toxic, so the model partially encodes "
      "the social act of group reporting rather than only lexical content.\"* "
      "What the paper treats as an interesting quirk of the LR coefficients "
      "is in fact a property of the label definition itself, affecting 580 "
      "test utterances — a quarter of the positive class. The sensitivity "
      "analysis in §11 is what turns that observation into a quantified "
      "threat-to-validity. "
      "The mapping is kept as the primary one because it is the one that "
      "reproduces the original counts, but every split also carries a "
      "`label_EI` column (`toxic = intentClass ∈ {E, I}`) so the sensitivity "
      "analysis can be run without re-deriving anything.")
    A("")

    # ---------------------------------------------------------------- splits
    A("## 3. Splits")
    A("")
    osp = old.get("splits", {})
    A("| split | n (new) | n (old) | toxic | % toxic | % toxic under `label_EI` |")
    A("|---|---|---|---|---|---|")
    keymap = {"train": "train_n", "val": "val_n", "test": "test_n"}
    for s in d01["splits"]:
        A("| {} | {} | {} | {} | {:.2f} | {:.2f} |".format(
            s["split"], s["n"], fmt(osp.get(keymap[s["split"]]), 0),
            s["toxic"], s["toxic_pct"], s["toxic_EI_pct"]))
    A("")
    same = (osp.get("train_n") == d01["splits"][0]["n"]
            and osp.get("val_n") == d01["splits"][1]["n"]
            and osp.get("test_n") == d01["splits"][2]["n"])
    A("Split sizes reproduce the original **exactly**: {}.".format(
        "yes" if same else "**NO — investigate**"))
    A("")

    # ---------------------------------------------------------------- preprocessing
    if d02:
        A("## 4. Preprocessing")
        A("")
        A("Classical pipeline order:")
        A("")
        for i, step in enumerate(d02["classical_order"], 1):
            A("{}. {}".format(i, step))
        A("")
        A("DistilBERT receives only: {}.".format(
            ", ".join(d02["bert_pipeline"])))
        A("")
        A("**Punctuation policy: `{}`.** {}".format(
            d02["punctuation_policy"], d02["punctuation_policy_note"]))
        A("")
        sw = d02["stopwords"]
        A("**The gaming stopword whitelist is a no-op.** None of "
          "`{}` appears in NLTK's English stopword list, so the effective "
          "stopword count is {} either way. Reported rather than silently "
          "dropped.".format(sw["whitelist"], sw["effective_count"]))
        A("")
        A("| split | n | empty after preprocessing | mean tokens | vocab |")
        A("|---|---|---|---|---|")
        for s in d02["splits"]:
            A("| {} | {} | {} ({:.2f}%) | {:.2f} | {} |".format(
                s["split"], s["n"], s["empty_after_classical"],
                s["empty_pct"], s["mean_tokens_classical"],
                s["vocab_size_classical"]))
        A("")

    # ---------------------------------------------------------------- hyperparams
    if d03:
        A("## 5. Model selection (never on test)")
        A("")
        oh = old.get("hyperparameters", {})
        A("| model | selected | how | value (new) | value (old) |")
        A("|---|---|---|---|---|")
        A("| LR | `C` | 5-fold CV on train, macro-F1 | {} | {} |".format(
            d03["models"]["LR"]["best_params"]["C"], fmt(oh.get("LR_C"), 2)))
        A("| NB | `alpha` | val split, macro-F1 | {} | {} |".format(
            d03["models"]["NB"]["best_params"]["alpha"],
            fmt(oh.get("NB_alpha"), 2)))
        A("| RF | `max_depth` | 5-fold CV on train, macro-F1 | {} | {} |".format(
            d03["models"]["RF"]["best_params"]["max_depth"],
            fmt(oh.get("RF_max_depth"), 0)))
        if d04:
            A("| DistilBERT | epoch | best val macro-F1 | {} | {} |".format(
                d04["best_epoch"], fmt(oh.get("distilbert_best_epoch"), 0)))
        A("")
        t = d03["tfidf"]
        A("TF-IDF: `ngram_range={}`, `max_features={}`, `sublinear_tf={}`, "
          "`min_df={}`, fitted on train only → {} features "
          "({} unigrams / {} bigrams).".format(
              t["ngram_range"], t["max_features"], t["sublinear_tf"],
              t["min_df"], t["vocab_size"], t["n_unigrams"], t["n_bigrams"]))
        A("")
        if d04:
            A("DistilBERT: {} epochs, best epoch {} (val macro-F1 {:.4f}), "
              "peak GPU memory {:.2f} GiB, total train time {:.1f} min on "
              "{}.".format(
                  d04["config"]["epochs"], d04["best_epoch"],
                  d04["best_val_macro_f1"], d04["peak_gpu_mem_gib"],
                  d04["total_train_seconds"] / 60, d04["device"]))
            A("")

    # ---------------------------------------------------------------- main metrics
    if d05:
        A("## 6. Main results — clean test set")
        A("")
        om = old.get("metrics", {})
        A("Format: `new (old) [delta]`. Threshold 0.5. "
          "n = {} ({} toxic / {} non-toxic).".format(
              d05["n_test"], d05["metrics"]["LR"]["n_toxic"],
              d05["metrics"]["LR"]["n_non_toxic"]))
        A("")
        A("| model | accuracy | macro-F1 | weighted-F1 | ROC-AUC | PR-AUC | "
          "recall (toxic) | FP count |")
        A("|---|---|---|---|---|---|---|---|")
        for m in MODELS:
            r = d05["metrics"][m]
            o = om.get(m, {})
            A("| **{}** | {} | {} | {} | {} | {} | {} | {} |".format(
                m,
                delta(r["accuracy"], o.get("accuracy")),
                delta(r["macro_f1"], o.get("macro_f1")),
                delta(r["weighted_f1"], o.get("weighted_f1")),
                delta(r["roc_auc"], o.get("roc_auc")),
                delta(r["pr_auc"], o.get("pr_auc")),
                delta(r["recall_toxic"], o.get("recall_toxic")),
                delta(r["false_positives"], o.get("false_positives"), 0)))
        A("")
        A("FP count = false positives among the {} non-toxic utterances.".format(
            d05["metrics"]["LR"]["n_non_toxic"]))
        A("")
        A("### 6.1 95% bootstrap CI on macro-F1")
        A("")
        b = d05["bootstrap"]
        A("{} resamples, seed {}, {} — resample indices shared across models "
          "so intervals are directly comparable.".format(
              b["n_resamples"], b["seed"], b["method"]))
        A("")
        A("| model | macro-F1 | 95% CI | width |")
        A("|---|---|---|---|")
        for m in MODELS:
            pm = b["per_model"][m]
            A("| {} | {:.4f} | [{:.4f}, {:.4f}] | {:.4f} |".format(
                m, d05["metrics"][m]["macro_f1"], pm["ci_low"],
                pm["ci_high"], pm["ci_high"] - pm["ci_low"]))
        A("")
        A("### 6.2 Pairwise McNemar")
        A("")
        A("`{}`. Rule: {}.".format(d05["mcnemar"]["library"],
                                   d05["mcnemar"]["rule"]))
        A("")
        omc = old.get("mcnemar_pvalues", {})
        A("| pair | discordant (b, c) | test used | statistic | p-value (new) "
          "| p-value (old) | significant (α=0.05) |")
        A("|---|---|---|---|---|---|---|")
        for pair, r in d05["mcnemar"]["pairs"].items():
            t = r["table"]
            op = omc.get(pair)
            A("| {} | {} ({}, {}) | {} | {} | {:.3e} | {} | {} |".format(
                pair, r["discordant"], t["only_A_correct"],
                t["only_B_correct"], r["test"],
                "n/a" if r["statistic"] is None
                else "{:.3f}".format(r["statistic"]),
                r["pvalue"],
                NR if op is None else "{:.1e}".format(op),
                "**yes**" if r["significant_at_0.05"] else "no"))
        A("")
        A("The paper reported all six pairs significant at α = 0.01. Any pair "
          "above that is *not* significant is a genuine disagreement with the "
          "old result, not a presentation difference.")
        A("")

    # ---------------------------------------------------------------- adversarial
    if d06:
        A("## 7. Adversarial robustness")
        A("")
        A("**Threat model.** {}".format(d06["threat_model"]))
        A("")
        A("Candidate-token rule: {}".format(d06["candidate_token_rule"]))
        A("")
        A("| attack | definition |")
        A("|---|---|")
        for k, v in d06["attacks"].items():
            A("| `{}` | {} |".format(k, v))
        A("")
        A("### 7.1 Macro-F1 under attack")
        A("")
        A("| model | clean | " + " | ".join("`{}`".format(a) for a in ATTACKS)
          + " |")
        A("|---" * (len(ATTACKS) + 2) + "|")
        for m in MODELS:
            cells = ["{:.4f}".format(d06["results"][a]["per_model"][m]["macro_f1"])
                     for a in ATTACKS]
            A("| **{}** | {:.4f} | {} |".format(
                m, d06["clean_macro_f1"][m], " | ".join(cells)))
        A("")
        A("### 7.2 Absolute drop from clean (higher = more fragile)")
        A("")
        oa = old.get("adversarial_macro_f1_drop", {})
        A("| model | " + " | ".join("`{}`".format(a) for a in ATTACKS) + " |")
        A("|---" * (len(ATTACKS) + 1) + "|")
        for m in MODELS:
            cells = []
            for a in ATTACKS:
                new = d06["results"][a]["per_model"][m]["abs_drop"]
                cells.append(delta(new, (oa.get(a) or {}).get(m)))
            A("| **{}** | {} |".format(m, " | ".join(cells)))
        A("")
        A("### 7.3 Ablation — classical defences disabled at inference")
        A("")
        A("{}".format(d06["ablation_note"]))
        A("")
        A("| config | model | clean | "
          + " | ".join("`{}`".format(a) for a in ATTACKS) + " |")
        A("|---" * (len(ATTACKS) + 3) + "|")
        for cfg, per in d06["ablation"].items():
            for m in ("LR", "NB", "RF"):
                row = per[m]
                cells = ["{:.4f} ({:+.3f})".format(
                    row[a]["macro_f1"], -row[a]["abs_drop"]) for a in ATTACKS]
                A("| `{}` | {} | {:.4f} | {} |".format(
                    cfg, m, row["clean"], " | ".join(cells)))
        A("")
        A("Cells are `macro-F1 (change vs that config's own clean score)`.")
        A("")
        A("### 7.4 Audit — what the vectoriser actually receives")
        A("")
        A("{} examples per attack were logged; the first 3 of each are shown "
          "here, the rest are in `results/06_adversarial.json` under "
          "`audit_samples`.".format(d06["n_audit_per_attack"]))
        A("")
        for a in ATTACKS:
            A("**`{}`**".format(a))
            A("")
            A("| raw | perturbed | reaches vectoriser as | in-vocab terms "
              "(clean → attacked) |")
            A("|---|---|---|---|")
            for s in d06["audit_samples"][a][:3]:
                A("| `{}` | `{}` | `{}` | {} → {} |".format(
                    s["raw"][:44].replace("|", "\\|"),
                    s["perturbed"][:44].replace("|", "\\|"),
                    s["vectorizer_input"][:44].replace("|", "\\|"),
                    s["n_in_vocab_clean"], s["n_in_vocab"]))
            A("")

    # ---------------------------------------------------------------- latency
    if d07:
        A("## 8. Inference latency")
        A("")
        p = d07["protocol"]
        A("{} warmup, {} timed single-example predictions, batch size {}, "
          "clock `{}`. **Primary metric: end-to-end.** {}".format(
              p["n_warmup"], p["n_timed"], p["batch_size"], p["clock"],
              p["primary_metric_note"]))
        A("")
        ol = old.get("latency_ms", {})
        A("| configuration | mean (ms) | p50 | p95 | p99 | model-only mean | "
          "batch-32 ex/s | batch-32 ms/ex | old mean |")
        A("|---|---|---|---|---|---|---|---|---|")

        def row(label, d, oldkey=None):
            e, mo, b = (d["end_to_end_single"], d["model_only_single"],
                        d["end_to_end_batch"])
            A("| {} | {:.3f} | {:.3f} | {:.3f} | {:.3f} | {:.3f} | {:.1f} | "
              "{:.3f} | {} |".format(
                  label, e["mean_ms"], e["p50_ms"], e["p95_ms"], e["p99_ms"],
                  mo["mean_ms"], b["throughput_examples_per_s"],
                  b["amortised_ms_per_example"],
                  fmt(ol.get(oldkey) if oldkey else None, 3)))

        cl = d07["cpu_classical"]
        row("LR (CPU)", cl["LR"], "LR")
        row("NB (CPU)", cl["NB"], "NB")
        row("RF `n_jobs=1` (CPU)", cl["RF"]["n_jobs=1"], "RF")
        row("RF `n_jobs=-1` (CPU)", cl["RF"]["n_jobs=-1"])
        row("DistilBERT (CPU)", d07["cpu_distilbert"], "DistilBERT_cpu")
        gpu = d07.get("gpu_distilbert", {})
        if "fp32" in gpu:
            row("DistilBERT (GPU fp32)", gpu["fp32"], "DistilBERT_gpu")
            row("DistilBERT (GPU fp16 autocast)", gpu["fp16_autocast"])
        A("")
        A("DistilBERT CPU used `torch.get_num_threads() = {}` "
          "(interop {}).".format(
              d07["cpu_distilbert"]["torch_num_threads"],
              d07["cpu_distilbert"]["torch_num_interop_threads"]))
        if "sync_note" in gpu:
            A("")
            A("GPU timing: {}.".format(gpu["sync_note"]))
        A("")
        rf1 = cl["RF"]["n_jobs=1"]["end_to_end_single"]["mean_ms"]
        rfp = cl["RF"]["n_jobs=-1"]["end_to_end_single"]["mean_ms"]
        A("**RF `n_jobs`:** single-example end-to-end is {:.3f} ms at "
          "`n_jobs=1` vs {:.3f} ms at `n_jobs=-1` — parallelism is "
          "{} on single examples ({:+.1f}%).".format(
              rf1, rfp, "a net loss" if rfp > rf1 else "a net win",
              100.0 * (rfp - rf1) / rf1))
        A("")

    # ---------------------------------------------------------------- cascade
    if d08:
        A("## 9. Cascade (LR first, DistilBERT on uncertainty)")
        A("")
        A("Rule: {}. Expected latency model: `{}`, using {}.".format(
            d08["rule"], d08["latency_model"], d08["latency_source"]))
        A("")
        for band, per in d08["results"].items():
            tag = " (default)" if band == "[0.4, 0.7]" else ""
            A("**Band {}{}**".format(band, tag))
            A("")
            A("| variant | escalated | macro-F1 | 95% CI | E[ms] BERT-CPU | "
              "E[ms] BERT-GPU |")
            A("|---|---|---|---|---|---|")
            for variant, r in per.items():
                A("| {} | {:.2f}% | {:.4f} | [{:.4f}, {:.4f}] | {} | {} |".format(
                    variant, 100 * r["escalation_rate"], r["macro_f1"],
                    r["bootstrap_ci"]["ci_low"], r["bootstrap_ci"]["ci_high"],
                    fmt(r["expected_ms_bert_cpu"], 3),
                    fmt(r["expected_ms_bert_gpu"], 3)))
            A("")
        A("Reference, no cascade:")
        A("")
        A("| variant | LR alone | DistilBERT alone |")
        A("|---|---|---|")
        for variant, r in d08["reference_no_cascade"].items():
            A("| {} | {:.4f} | {:.4f} |".format(
                variant, r["LR_only_macro_f1"], r["DistilBERT_only_macro_f1"]))
        A("")

    # ---------------------------------------------------------------- analysis
    if d09:
        A("## 10. Error analysis and interpretation")
        A("")
        A("### 10.1 Top {} LR coefficients".format(d09["top_k"]))
        A("")
        A("| rank | → toxic | coef | → non-toxic | coef |")
        A("|---|---|---|---|---|")
        pos = d09["lr_coefficients"]["top_positive"]
        neg = d09["lr_coefficients"]["top_negative"]
        for i in range(len(pos)):
            A("| {} | `{}` | {:+.4f} | `{}` | {:+.4f} |".format(
                i + 1, pos[i]["surface_forms"], pos[i]["coefficient"],
                neg[i]["surface_forms"], neg[i]["coefficient"]))
        A("")
        A("Features are Porter stems; bracketed forms are the training-set "
          "surface words mapping onto that stem.")
        A("")
        for mdl, e in d09["error_analysis"].items():
            A("### 10.2 {} — highest-confidence errors".format(mdl))
            A("")
            A("{} false positives and {} false negatives in total. "
              "By gold intent class — FP: `{}`; FN: `{}`.".format(
                  e["n_fp_total"], e["n_fn_total"],
                  e["fp_by_intent"], e["fn_by_intent"]))
            A("")
            A("**False positives** (gold non-toxic, predicted toxic)")
            A("")
            A("| # | P(toxic) | intent | utterance |")
            A("|---|---|---|---|")
            for s in e["false_positives"]:
                A("| {} | {:.4f} | `{}` | `{}` |".format(
                    s["rank"], s["p_toxic"], s["intent_class"],
                    s["utterance"][:88].replace("|", "\\|")))
            A("")
            A("**False negatives** (gold toxic, predicted non-toxic)")
            A("")
            A("| # | P(toxic) | intent | utterance |")
            A("|---|---|---|---|")
            for s in e["false_negatives"]:
                A("| {} | {:.4f} | `{}` | `{}` |".format(
                    s["rank"], s["p_toxic"], s["intent_class"],
                    s["utterance"][:88].replace("|", "\\|")))
            A("")

    # ---------------------------------------------------------------- sensitivity
    A("## 11. Sensitivity analysis — the `E ∪ I` label definition")
    A("")
    if not has_ei:
        A("_Not yet produced._ Run the whole pipeline again with "
          "`TOX_LABEL_SET=ei` (scripts 03–10) to populate this section.")
        A("")
    else:
        A("The primary mapping labels CONDA's `A` (action) class toxic because "
          "that is what reproduces the original counts. This section re-runs "
          "the entire pipeline — separate TF-IDF fit, separate hyperparameter "
          "selection, a separately fine-tuned DistilBERT — against "
          "`toxic = intentClass ∈ {E, I}` (1,765 toxic / 7,208 non-toxic), the "
          "dataset authors' own definition. Nothing is shared between the two "
          "runs except the raw text and the splits.")
        A("")
        A("### 11.1 Main metrics under both label definitions")
        A("")
        A("| model | macro-F1 (primary `E∪A∪I`) | macro-F1 (sensitivity `E∪I`) "
          "| Δ | recall toxic (primary) | recall toxic (`E∪I`) |")
        A("|---|---|---|---|---|---|")
        for m in MODELS:
            a = d05["metrics"][m]["macro_f1"] if d05 else None
            b = e05["metrics"][m]["macro_f1"]
            ra = d05["metrics"][m]["recall_toxic"] if d05 else None
            rb = e05["metrics"][m]["recall_toxic"]
            A("| **{}** | {} | {:.4f} | {} | {} | {:.4f} |".format(
                m, fmt(a), b,
                "n/a" if a is None else "{:+.4f}".format(b - a),
                fmt(ra), rb))
        A("")
        if e03:
            A("Selected hyperparameters differ between label sets:")
            A("")
            A("| model | primary | sensitivity `E∪I` |")
            A("|---|---|---|")
            A("| LR `C` | {} | {} |".format(
                d03["models"]["LR"]["best_params"]["C"],
                e03["models"]["LR"]["best_params"]["C"]))
            A("| NB `alpha` | {} | {} |".format(
                d03["models"]["NB"]["best_params"]["alpha"],
                e03["models"]["NB"]["best_params"]["alpha"]))
            A("| RF `max_depth` | {} | {} |".format(
                d03["models"]["RF"]["best_params"]["max_depth"],
                e03["models"]["RF"]["best_params"]["max_depth"]))
            if d04 and e04:
                A("| DistilBERT best epoch | {} | {} |".format(
                    d04["best_epoch"], e04["best_epoch"]))
            A("")
        if e06 and d06:
            A("### 11.2 Adversarial drop under both label definitions")
            A("")
            A("| model | " + " | ".join(
                "`{}` primary / `E∪I`".format(a) for a in ATTACKS) + " |")
            A("|---" * (len(ATTACKS) + 1) + "|")
            for m in MODELS:
                cells = []
                for a in ATTACKS:
                    pa = d06["results"][a]["per_model"][m]["abs_drop"]
                    pb = e06["results"][a]["per_model"][m]["abs_drop"]
                    cells.append("{:.4f} / {:.4f}".format(pa, pb))
                A("| **{}** | {} |".format(m, " | ".join(cells)))
            A("")
        if e08 and d08:
            A("### 11.3 Cascade under both label definitions (default band)")
            A("")
            A("| variant | escalated (primary) | escalated (`E∪I`) | "
              "macro-F1 (primary) | macro-F1 (`E∪I`) |")
            A("|---|---|---|---|---|")
            pb = d08["results"].get("[0.4, 0.7]", {})
            eb = e08["results"].get("[0.4, 0.7]", {})
            for variant in pb:
                if variant not in eb:
                    continue
                A("| {} | {:.2f}% | {:.2f}% | {:.4f} | {:.4f} |".format(
                    variant, 100 * pb[variant]["escalation_rate"],
                    100 * eb[variant]["escalation_rate"],
                    pb[variant]["macro_f1"], eb[variant]["macro_f1"]))
            A("")

    # ---------------------------------------------------------------- conclusions
    A("## 12. Conclusions, flip check, and label-definition robustness")
    A("")
    oc = old.get("conclusions", {})
    concl = conclusions_from(d05, d06, d07, d08)
    drops = concl.pop("_mean_drops", None)
    concl_ei = conclusions_from(e05, e06, e07 or d07, e08) if has_ei else {}
    drops_ei = concl_ei.pop("_mean_drops", None) if concl_ei else None

    if has_ei:
        A("### 12.1 Does each conclusion survive the label change?")
        A("")
        A("A claim that holds under the primary mapping but not under `E∪I` is "
          "an artefact of labelling the action class toxic, and should not be "
          "stated unconditionally in the paper.")
        A("")
        A("| claim | primary `E∪A∪I` | sensitivity `E∪I` | robust to label "
          "definition? |")
        A("|---|---|---|---|")
        fragile = []
        for k in concl:
            if k not in concl_ei:
                continue
            same = bool(concl[k]) == bool(concl_ei[k])
            if not same:
                fragile.append(k)
            A("| `{}` | {} | {} | {} |".format(
                k, concl[k], concl_ei[k],
                "yes" if same else "**NO — label-dependent**"))
        A("")
        if fragile:
            A("**Label-dependent conclusions — do not state these without the "
              "caveat:**")
            A("")
            for f in fragile:
                A("- `{}`: `{}` under the primary mapping, `{}` under "
                  "`E∪I`.".format(f, concl[f], concl_ei[f]))
            A("")
        else:
            A("Every recomputed conclusion survives the label change.")
            A("")

    A("### 12.2 Against the old paper")
    A("")
    A("| claim | this rebuild | old paper | status |")
    A("|---|---|---|---|")
    flips = []
    for k, v in concl.items():
        o = oc.get(k)
        if o is None:
            status = "no old value — cannot compare"
        elif bool(o) == bool(v):
            status = "consistent"
        else:
            status = "**FLIPPED**"
            flips.append(k)
        A("| `{}` | {} | {} | {} |".format(
            k, v, NR if o is None else o, status))
    A("")
    if flips:
        A("### Conclusions that FLIPPED")
        A("")
        for f in flips:
            A("- **`{}`** — was `{}`, now `{}`.".format(f, oc.get(f), concl[f]))
        A("")
    else:
        A("No flips detected against recorded old claims. Note that most old "
          "claims were *not recorded*, so this is an absence of evidence, not "
          "evidence of agreement.")
        A("")

    if drops:
        A("### 12.3 Observed robustness ordering (this rebuild)")
        A("")
        A("Mean absolute macro-F1 drop across the four attacks "
          "(lower = more robust):")
        A("")
        if drops_ei:
            A("| model | mean drop (primary) | mean drop (`E∪I`) |")
            A("|---|---|---|")
            for m, v in sorted(drops.items(), key=lambda kv: kv[1]):
                A("| {} | {:.4f} | {:.4f} |".format(m, v, drops_ei[m]))
        else:
            A("| model | mean drop |")
            A("|---|---|")
            for m, v in sorted(drops.items(), key=lambda kv: kv[1]):
                A("| {} | {:.4f} |".format(m, v))
        A("")

    A("## 13. Open items")
    A("")
    A("- `results/old_paper.json` is mostly empty: no metric values survived "
      "the deletion, so every old-vs-new cell above reads *not recorded*. The "
      "paper should not imply a comparison that could not be made. Fill the "
      "file in and re-run this script if the old draft turns up.")
    if has_ei:
        A("- The sensitivity run (§11) is complete. Any claim marked "
          "label-dependent in §12.1 needs the `A`-class caveat stated "
          "alongside it.")
    else:
        A("- The `E∪I` sensitivity run (§11) has not been produced yet: "
          "`TOX_LABEL_SET=ei` for scripts 03–10.")
    A("- The gaming stopword whitelist (§4) currently changes nothing; either "
      "drop the claim from the paper or widen the stopword list it subtracts "
      "from.")
    A("")

    out = C.RESULTS / "SUMMARY.md"
    out.write_text("\n".join(L), encoding="utf-8")
    print("[saved] SUMMARY.md -> {}  ({} lines)".format(
        out.relative_to(C.ROOT), len(L)))
    if flips:
        print("\n  *** {} conclusion(s) FLIPPED: {}".format(len(flips), flips))


if __name__ == "__main__":
    main()
